//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoParts_ShopAndForum.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoParts_ShopAndForum.Localization.MainLocalization", typeof(MainLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Или използвай локален акаунт за вход.
        /// </summary>
        public static string Account_LoginWithLocalAccount {
            get {
                return ResourceManager.GetString("Account_LoginWithLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрирай се като нов потребител.
        /// </summary>
        public static string Account_RegisterAsNewUser {
            get {
                return ResourceManager.GetString("Account_RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави продукт.
        /// </summary>
        public static string AddProduct_Navigation {
            get {
                return ResourceManager.GetString("AddProduct_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не бяха открити поръчки..
        /// </summary>
        public static string AdministrationOrders_NoOrdersFound {
            get {
                return ResourceManager.GetString("AdministrationOrders_NoOrdersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поръчки.
        /// </summary>
        public static string AdminOrders_Navigation {
            get {
                return ResourceManager.GetString("AdminOrders_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Админ панел.
        /// </summary>
        public static string AdminPanel_Navigation {
            get {
                return ResourceManager.GetString("AdminPanel_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукти.
        /// </summary>
        public static string AllProducts_Navigation {
            get {
                return ResourceManager.GetString("AllProducts_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количка.
        /// </summary>
        public static string Cart_CartItem {
            get {
                return ResourceManager.GetString("Cart_CartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Безплатна доставка.
        /// </summary>
        public static string Cart_FreeShipping {
            get {
                return ResourceManager.GetString("Cart_FreeShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финализиране на поръчката.
        /// </summary>
        public static string Cart_GoToCheckout {
            get {
                return ResourceManager.GetString("Cart_GoToCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to артикул.
        /// </summary>
        public static string Cart_Item {
            get {
                return ResourceManager.GetString("Cart_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to артикула.
        /// </summary>
        public static string Cart_Items {
            get {
                return ResourceManager.GetString("Cart_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количка.
        /// </summary>
        public static string Cart_PageTitle {
            get {
                return ResourceManager.GetString("Cart_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукти.
        /// </summary>
        public static string Cart_ProductsPrice {
            get {
                return ResourceManager.GetString("Cart_ProductsPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Cart_Quantity {
            get {
                return ResourceManager.GetString("Cart_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий.
        /// </summary>
        public static string Cart_RemoveItem {
            get {
                return ResourceManager.GetString("Cart_RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка.
        /// </summary>
        public static string Cart_ShippingPrice {
            get {
                return ResourceManager.GetString("Cart_ShippingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Единична цена.
        /// </summary>
        public static string Cart_SinglePrice {
            get {
                return ResourceManager.GetString("Cart_SinglePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайна цена.
        /// </summary>
        public static string Cart_TotalAmount {
            get {
                return ResourceManager.GetString("Cart_TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн поддръжка.
        /// </summary>
        public static string Chat_Navigation {
            get {
                return ResourceManager.GetString("Chat_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Финализиране на поръчка.
        /// </summary>
        public static string Checkout_Title {
            get {
                return ResourceManager.GetString("Checkout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лева.
        /// </summary>
        public static string Currency_Name {
            get {
                return ResourceManager.GetString("Currency_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продуктови прогнози.
        /// </summary>
        public static string ForecastProduct_Navigation {
            get {
                return ResourceManager.GetString("ForecastProduct_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форум.
        /// </summary>
        public static string Forum_Navigation {
            get {
                return ResourceManager.GetString("Forum_Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на нов пост.
        /// </summary>
        public static string ForumCategories_CreateNewPost {
            get {
                return ResourceManager.GetString("ForumCategories_CreateNewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории.
        /// </summary>
        public static string ForumCategories_Title {
            get {
                return ResourceManager.GetString("ForumCategories_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн авточасти.
        /// </summary>
        public static string Home_PageTitle {
            get {
                return ResourceManager.GetString("Home_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете поне {1} символа за полето &quot;{0}&quot;.
        /// </summary>
        public static string InputFieldAtLeastLength {
            get {
                return ResourceManager.GetString("InputFieldAtLeastLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;{0}&quot; трябва да има стойност.
        /// </summary>
        public static string InputFieldRequired {
            get {
                return ResourceManager.GetString("InputFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LoginNavigation {
            get {
                return ResourceManager.GetString("LoginNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички.
        /// </summary>
        public static string OrderQueryViewModel_AllPages {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на създаване - възходящ.
        /// </summary>
        public static string OrderQueryViewModel_DateCreatedAscending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_DateCreatedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на създаване - низходящ.
        /// </summary>
        public static string OrderQueryViewModel_DateCreatedDescending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_DateCreatedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на доставяне - възходящ.
        /// </summary>
        public static string OrderQueryViewModel_DateDeliveredAscending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_DateDeliveredAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на доставяне - низходящ.
        /// </summary>
        public static string OrderQueryViewModel_DateDeliveredDescending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_DateDeliveredDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без сортиране.
        /// </summary>
        public static string OrderQueryViewModel_NoSorting {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_NoSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички.
        /// </summary>
        public static string OrderQueryViewModel_StatusFilterAll {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_StatusFilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставена.
        /// </summary>
        public static string OrderQueryViewModel_StatusFilterDelivered {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_StatusFilterDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В процес на доставка.
        /// </summary>
        public static string OrderQueryViewModel_StatusFilterPending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_StatusFilterPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайна цена - възходящ.
        /// </summary>
        public static string OrderQueryViewModel_TotalAscending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_TotalAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крайна цена - низходящ.
        /// </summary>
        public static string OrderQueryViewModel_TotalDescending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_TotalDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставена.
        /// </summary>
        public static string OrderStatus_Delivered {
            get {
                return ResourceManager.GetString("OrderStatus_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешно онлайн заплащане.
        /// </summary>
        public static string OrderStatus_FailedOnlinePayment {
            get {
                return ResourceManager.GetString("OrderStatus_FailedOnlinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В процес на доставка.
        /// </summary>
        public static string OrderStatus_Pending {
            get {
                return ResourceManager.GetString("OrderStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на създаване.
        /// </summary>
        public static string OrderSummary_DateCreated {
            get {
                return ResourceManager.GetString("OrderSummary_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на доставяне.
        /// </summary>
        public static string OrderSummary_DateDelivered {
            get {
                return ResourceManager.GetString("OrderSummary_DateDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string OrderSummary_OrderId {
            get {
                return ResourceManager.GetString("OrderSummary_OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string OrderSummary_OrderStatus {
            get {
                return ResourceManager.GetString("OrderSummary_OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тотал.
        /// </summary>
        public static string OrderSummary_OverallSum {
            get {
                return ResourceManager.GetString("OrderSummary_OverallSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начин на плащане.
        /// </summary>
        public static string OrderSummary_PayWay {
            get {
                return ResourceManager.GetString("OrderSummary_PayWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string OrderSummary_Username {
            get {
                return ResourceManager.GetString("OrderSummary_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наложен платеж.
        /// </summary>
        public static string OrderSummaryViewModel_CashOnDeliveryPayWay {
            get {
                return ResourceManager.GetString("OrderSummaryViewModel_CashOnDeliveryPayWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Онлайн плащане.
        /// </summary>
        public static string OrderSummaryViewModel_OnlinePayWay {
            get {
                return ResourceManager.GetString("OrderSummaryViewModel_OnlinePayWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Най-добрите добавки.
        /// </summary>
        public static string PostCategory_BestAdditives {
            get {
                return ResourceManager.GetString("PostCategory_BestAdditives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Най-добрите филтри.
        /// </summary>
        public static string PostCategory_BestFilters {
            get {
                return ResourceManager.GetString("PostCategory_BestFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Най-добрите масла.
        /// </summary>
        public static string PostCategory_BestOils {
            get {
                return ResourceManager.GetString("PostCategory_BestOils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Списък с постове.
        /// </summary>
        public static string PostList_Title {
            get {
                return ResourceManager.GetString("PostList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string PostListViewModel_Author {
            get {
                return ResourceManager.GetString("PostListViewModel_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой коментари.
        /// </summary>
        public static string PostListViewModel_CommentsCount {
            get {
                return ResourceManager.GetString("PostListViewModel_CommentsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на създаване.
        /// </summary>
        public static string PostListViewModel_DateCreate {
            get {
                return ResourceManager.GetString("PostListViewModel_DateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавие.
        /// </summary>
        public static string PostListViewModel_Title {
            get {
                return ResourceManager.GetString("PostListViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string ProductAdd_Description {
            get {
                return ResourceManager.GetString("ProductAdd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публичен URL до снимка.
        /// </summary>
        public static string ProductAdd_ImageUrl {
            get {
                return ResourceManager.GetString("ProductAdd_ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string ProductAdd_Name {
            get {
                return ResourceManager.GetString("ProductAdd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на продукт.
        /// </summary>
        public static string ProductAdd_PageTitle {
            get {
                return ResourceManager.GetString("ProductAdd_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string ProductAdd_Price {
            get {
                return ResourceManager.GetString("ProductAdd_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля въведете стойност между {1} и {2} за полето &quot;{0}&quot;.
        /// </summary>
        public static string ProductAdd_PriceRange {
            get {
                return ResourceManager.GetString("ProductAdd_PriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подкатегория.
        /// </summary>
        public static string ProductAdd_SelectedSubcategory {
            get {
                return ResourceManager.GetString("ProductAdd_SelectedSubcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложи.
        /// </summary>
        public static string ProductAll_Apply {
            get {
                return ResourceManager.GetString("ProductAll_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купи.
        /// </summary>
        public static string ProductAll_Buy {
            get {
                return ResourceManager.GetString("ProductAll_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай.
        /// </summary>
        public static string ProductAll_Edit {
            get {
                return ResourceManager.GetString("ProductAll_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напред.
        /// </summary>
        public static string ProductAll_NextPage {
            get {
                return ResourceManager.GetString("ProductAll_NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string ProductAll_PreviousPage {
            get {
                return ResourceManager.GetString("ProductAll_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нулирай.
        /// </summary>
        public static string ProductAll_Reset {
            get {
                return ResourceManager.GetString("ProductAll_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подкатегории.
        /// </summary>
        public static string ProductAll_Subcategories {
            get {
                return ResourceManager.GetString("ProductAll_Subcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филтри.
        /// </summary>
        public static string ProductCategory_Filters {
            get {
                return ResourceManager.GetString("ProductCategory_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масла и течности.
        /// </summary>
        public static string ProductCategory_OilsAndLiquids {
            get {
                return ResourceManager.GetString("ProductCategory_OilsAndLiquids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почистване на стъкла.
        /// </summary>
        public static string ProductCategory_WindowsCleaning {
            get {
                return ResourceManager.GetString("ProductCategory_WindowsCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добави в количката.
        /// </summary>
        public static string ProductDetails_AddToCart {
            get {
                return ResourceManager.GetString("ProductDetails_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за продукт.
        /// </summary>
        public static string ProductDetails_PageTitle {
            get {
                return ResourceManager.GetString("ProductDetails_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string ProductDetails_PreviousPage {
            get {
                return ResourceManager.GetString("ProductDetails_PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} е успешно добавен в количката.
        /// </summary>
        public static string ProductDetails_ProductSuccessfullyAddedToCart {
            get {
                return ResourceManager.GetString("ProductDetails_ProductSuccessfullyAddedToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string ProductDetails_Quantity {
            get {
                return ResourceManager.GetString("ProductDetails_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички.
        /// </summary>
        public static string ProductQueryViewModel_AllPages {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на добавяне - възходяш.
        /// </summary>
        public static string ProductQueryViewModel_DateAddedAscending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_DateAddedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на добавяне - низходящ.
        /// </summary>
        public static string ProductQueryViewModel_DateAddedDescending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_DateAddedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име - възходящ.
        /// </summary>
        public static string ProductQueryViewModel_NameAscending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_NameAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име - низходящ.
        /// </summary>
        public static string ProductQueryViewModel_NameDescending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_NameDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Без сортиране.
        /// </summary>
        public static string ProductQueryViewModel_NoSorting {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_NoSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена - възходящ.
        /// </summary>
        public static string ProductQueryViewModel_PriceAscending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_PriceAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена - низходящ.
        /// </summary>
        public static string ProductQueryViewModel_PriceDescending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_PriceDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавки.
        /// </summary>
        public static string ProductsCategory_Additives {
            get {
                return ResourceManager.GetString("ProductsCategory_Additives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въздушни филтри.
        /// </summary>
        public static string ProductSubcategory_AirFilters {
            get {
                return ResourceManager.GetString("ProductSubcategory_AirFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Антифриз.
        /// </summary>
        public static string ProductSubcategory_Antifreeze {
            get {
                return ResourceManager.GetString("ProductSubcategory_Antifreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почистване на задно стъкло.
        /// </summary>
        public static string ProductSubcategory_BackWindow {
            get {
                return ResourceManager.GetString("ProductSubcategory_BackWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавки за охладителна течност.
        /// </summary>
        public static string ProductSubcategory_CoolantAdditives {
            get {
                return ResourceManager.GetString("ProductSubcategory_CoolantAdditives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почистване на предно стъкло.
        /// </summary>
        public static string ProductSubcategory_FrontWindow {
            get {
                return ResourceManager.GetString("ProductSubcategory_FrontWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавки за маслена система.
        /// </summary>
        public static string ProductSubcategory_OilAdditives {
            get {
                return ResourceManager.GetString("ProductSubcategory_OilAdditives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маслени филтри.
        /// </summary>
        public static string ProductSubcategory_OilFilters {
            get {
                return ResourceManager.GetString("ProductSubcategory_OilFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Масла.
        /// </summary>
        public static string ProductSubcategory_Oils {
            get {
                return ResourceManager.GetString("ProductSubcategory_Oils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register_Navigation {
            get {
                return ResourceManager.GetString("Register_Navigation", resourceCulture);
            }
        }
    }
}
