//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoParts_ShopAndForum.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLocalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLocalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AutoParts_ShopAndForum.Localization.MainLocalization", typeof(MainLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        public static string Account_LoginWithLocalAccount {
            get {
                return ResourceManager.GetString("Account_LoginWithLocalAccount", resourceCulture);
            }
        }
        
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        public static string Account_RegisterAsNewUser {
            get {
                return ResourceManager.GetString("Account_RegisterAsNewUser", resourceCulture);
            }
        }
        
        public static string AddProduct_Navigation {
            get {
                return ResourceManager.GetString("AddProduct_Navigation", resourceCulture);
            }
        }
        
        public static string AllProducts_Navigation {
            get {
                return ResourceManager.GetString("AllProducts_Navigation", resourceCulture);
            }
        }
        
        public static string Chat_Navigation {
            get {
                return ResourceManager.GetString("Chat_Navigation", resourceCulture);
            }
        }
        
        public static string Forum_Navigation {
            get {
                return ResourceManager.GetString("Forum_Navigation", resourceCulture);
            }
        }
        
        public static string LoginNavigation {
            get {
                return ResourceManager.GetString("LoginNavigation", resourceCulture);
            }
        }
        
        public static string PostCategory_BestAdditives {
            get {
                return ResourceManager.GetString("PostCategory_BestAdditives", resourceCulture);
            }
        }
        
        public static string PostCategory_BestFilters {
            get {
                return ResourceManager.GetString("PostCategory_BestFilters", resourceCulture);
            }
        }
        
        public static string PostCategory_BestOils {
            get {
                return ResourceManager.GetString("PostCategory_BestOils", resourceCulture);
            }
        }
        
        public static string ProductCategory_Filters {
            get {
                return ResourceManager.GetString("ProductCategory_Filters", resourceCulture);
            }
        }
        
        public static string ProductCategory_OilsAndLiquids {
            get {
                return ResourceManager.GetString("ProductCategory_OilsAndLiquids", resourceCulture);
            }
        }
        
        public static string ProductCategory_WindowsCleaning {
            get {
                return ResourceManager.GetString("ProductCategory_WindowsCleaning", resourceCulture);
            }
        }
        
        public static string ProductsCategory_Additives {
            get {
                return ResourceManager.GetString("ProductsCategory_Additives", resourceCulture);
            }
        }
        
        public static string ProductSubcategory_AirFilters {
            get {
                return ResourceManager.GetString("ProductSubcategory_AirFilters", resourceCulture);
            }
        }
        
        public static string ProductSubcategory_Antifreeze {
            get {
                return ResourceManager.GetString("ProductSubcategory_Antifreeze", resourceCulture);
            }
        }
        
        public static string ProductSubcategory_BackWindow {
            get {
                return ResourceManager.GetString("ProductSubcategory_BackWindow", resourceCulture);
            }
        }
        
        public static string ProductSubcategory_CoolantAdditives {
            get {
                return ResourceManager.GetString("ProductSubcategory_CoolantAdditives", resourceCulture);
            }
        }
        
        public static string ProductSubcategory_FrontWindow {
            get {
                return ResourceManager.GetString("ProductSubcategory_FrontWindow", resourceCulture);
            }
        }
        
        public static string ProductSubcategory_OilAdditives {
            get {
                return ResourceManager.GetString("ProductSubcategory_OilAdditives", resourceCulture);
            }
        }
        
        public static string ProductSubcategory_OilFilters {
            get {
                return ResourceManager.GetString("ProductSubcategory_OilFilters", resourceCulture);
            }
        }
        
        public static string ProductSubcategory_Oils {
            get {
                return ResourceManager.GetString("ProductSubcategory_Oils", resourceCulture);
            }
        }
        
        public static string Register_Navigation {
            get {
                return ResourceManager.GetString("Register_Navigation", resourceCulture);
            }
        }
        
        public static string ProductAdd_Name {
            get {
                return ResourceManager.GetString("ProductAdd_Name", resourceCulture);
            }
        }
        
        public static string InputFieldRequired {
            get {
                return ResourceManager.GetString("InputFieldRequired", resourceCulture);
            }
        }
        
        public static string InputFieldAtLeastLength {
            get {
                return ResourceManager.GetString("InputFieldAtLeastLength", resourceCulture);
            }
        }
        
        public static string ProductAdd_ImageUrl {
            get {
                return ResourceManager.GetString("ProductAdd_ImageUrl", resourceCulture);
            }
        }
        
        public static string ProductAdd_Price {
            get {
                return ResourceManager.GetString("ProductAdd_Price", resourceCulture);
            }
        }
        
        public static string ProductAdd_PriceRange {
            get {
                return ResourceManager.GetString("ProductAdd_PriceRange", resourceCulture);
            }
        }
        
        public static string ProductAdd_Description {
            get {
                return ResourceManager.GetString("ProductAdd_Description", resourceCulture);
            }
        }
        
        public static string ProductAdd_SelectedSubcategory {
            get {
                return ResourceManager.GetString("ProductAdd_SelectedSubcategory", resourceCulture);
            }
        }
        
        public static string ProductAdd_PageTitle {
            get {
                return ResourceManager.GetString("ProductAdd_PageTitle", resourceCulture);
            }
        }
        
        public static string Home_PageTitle {
            get {
                return ResourceManager.GetString("Home_PageTitle", resourceCulture);
            }
        }
        
        public static string ProductQueryViewModel_NoSorting {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_NoSorting", resourceCulture);
            }
        }
        
        public static string ProductQueryViewModel_PriceAscending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_PriceAscending", resourceCulture);
            }
        }
        
        public static string ProductQueryViewModel_PriceDescending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_PriceDescending", resourceCulture);
            }
        }
        
        public static string ProductQueryViewModel_NameAscending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_NameAscending", resourceCulture);
            }
        }
        
        public static string ProductQueryViewModel_NameDescending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_NameDescending", resourceCulture);
            }
        }
        
        public static string ProductQueryViewModel_DateAddedAscending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_DateAddedAscending", resourceCulture);
            }
        }
        
        public static string ProductQueryViewModel_DateAddedDescending {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_DateAddedDescending", resourceCulture);
            }
        }
        
        public static string ProductQueryViewModel_AllPages {
            get {
                return ResourceManager.GetString("ProductQueryViewModel_AllPages", resourceCulture);
            }
        }
        
        public static string ProductAll_NextPage {
            get {
                return ResourceManager.GetString("ProductAll_NextPage", resourceCulture);
            }
        }
        
        public static string ProductAll_PreviousPage {
            get {
                return ResourceManager.GetString("ProductAll_PreviousPage", resourceCulture);
            }
        }
        
        public static string ProductAll_Apply {
            get {
                return ResourceManager.GetString("ProductAll_Apply", resourceCulture);
            }
        }
        
        public static string ProductAll_Reset {
            get {
                return ResourceManager.GetString("ProductAll_Reset", resourceCulture);
            }
        }
        
        public static string ProductAll_Subcategories {
            get {
                return ResourceManager.GetString("ProductAll_Subcategories", resourceCulture);
            }
        }
        
        public static string ProductAll_Buy {
            get {
                return ResourceManager.GetString("ProductAll_Buy", resourceCulture);
            }
        }
        
        public static string ProductAll_Edit {
            get {
                return ResourceManager.GetString("ProductAll_Edit", resourceCulture);
            }
        }
        
        public static string Currency_Name {
            get {
                return ResourceManager.GetString("Currency_Name", resourceCulture);
            }
        }
        
        public static string ProductDetails_PageTitle {
            get {
                return ResourceManager.GetString("ProductDetails_PageTitle", resourceCulture);
            }
        }
        
        public static string ProductDetails_PreviousPage {
            get {
                return ResourceManager.GetString("ProductDetails_PreviousPage", resourceCulture);
            }
        }
        
        public static string ProductDetails_Quantity {
            get {
                return ResourceManager.GetString("ProductDetails_Quantity", resourceCulture);
            }
        }
        
        public static string ProductDetails_AddToCart {
            get {
                return ResourceManager.GetString("ProductDetails_AddToCart", resourceCulture);
            }
        }
        
        public static string ProductDetails_ProductSuccessfullyAddedToCart {
            get {
                return ResourceManager.GetString("ProductDetails_ProductSuccessfullyAddedToCart", resourceCulture);
            }
        }
        
        public static string Cart_PageTitle {
            get {
                return ResourceManager.GetString("Cart_PageTitle", resourceCulture);
            }
        }
        
        public static string Cart_CartItem {
            get {
                return ResourceManager.GetString("Cart_CartItem", resourceCulture);
            }
        }
        
        public static string Cart_Items {
            get {
                return ResourceManager.GetString("Cart_Items", resourceCulture);
            }
        }
        
        public static string Cart_Item {
            get {
                return ResourceManager.GetString("Cart_Item", resourceCulture);
            }
        }
        
        public static string Cart_RemoveItem {
            get {
                return ResourceManager.GetString("Cart_RemoveItem", resourceCulture);
            }
        }
        
        public static string Cart_GoToCheckout {
            get {
                return ResourceManager.GetString("Cart_GoToCheckout", resourceCulture);
            }
        }
        
        public static string Cart_Quantity {
            get {
                return ResourceManager.GetString("Cart_Quantity", resourceCulture);
            }
        }
        
        public static string Cart_SinglePrice {
            get {
                return ResourceManager.GetString("Cart_SinglePrice", resourceCulture);
            }
        }
        
        public static string Cart_ProductsPrice {
            get {
                return ResourceManager.GetString("Cart_ProductsPrice", resourceCulture);
            }
        }
        
        public static string Cart_ShippingPrice {
            get {
                return ResourceManager.GetString("Cart_ShippingPrice", resourceCulture);
            }
        }
        
        public static string Cart_FreeShipping {
            get {
                return ResourceManager.GetString("Cart_FreeShipping", resourceCulture);
            }
        }
        
        public static string Cart_TotalAmount {
            get {
                return ResourceManager.GetString("Cart_TotalAmount", resourceCulture);
            }
        }
        
        public static string ForecastProduct_Navigation {
            get {
                return ResourceManager.GetString("ForecastProduct_Navigation", resourceCulture);
            }
        }
        
        public static string AdminPanel_Navigation {
            get {
                return ResourceManager.GetString("AdminPanel_Navigation", resourceCulture);
            }
        }
        
        public static string OrderStatus_Delivered {
            get {
                return ResourceManager.GetString("OrderStatus_Delivered", resourceCulture);
            }
        }
        
        public static string OrderStatus_Pending {
            get {
                return ResourceManager.GetString("OrderStatus_Pending", resourceCulture);
            }
        }
        
        public static string OrderStatus_FailedOnlinePayment {
            get {
                return ResourceManager.GetString("OrderStatus_FailedOnlinePayment", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_AllPages {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_AllPages", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_NoSorting {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_NoSorting", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_TotalAscending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_TotalAscending", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_TotalDescending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_TotalDescending", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_DateCreatedAscending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_DateCreatedAscending", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_DateCreatedDescending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_DateCreatedDescending", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_DateDeliveredAscending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_DateDeliveredAscending", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_DateDeliveredDescending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_DateDeliveredDescending", resourceCulture);
            }
        }
        
        public static string AdminOrders_Navigation {
            get {
                return ResourceManager.GetString("AdminOrders_Navigation", resourceCulture);
            }
        }
        
        public static string OrderSummaryViewModel_OnlinePayWay {
            get {
                return ResourceManager.GetString("OrderSummaryViewModel_OnlinePayWay", resourceCulture);
            }
        }
        
        public static string OrderSummaryViewModel_CashOnDeliveryPayWay {
            get {
                return ResourceManager.GetString("OrderSummaryViewModel_CashOnDeliveryPayWay", resourceCulture);
            }
        }
        
        public static string AdministrationOrders_NoOrdersFound {
            get {
                return ResourceManager.GetString("AdministrationOrders_NoOrdersFound", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_StatusFilterAll {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_StatusFilterAll", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_StatusFilterDelivered {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_StatusFilterDelivered", resourceCulture);
            }
        }
        
        public static string OrderQueryViewModel_StatusFilterPending {
            get {
                return ResourceManager.GetString("OrderQueryViewModel_StatusFilterPending", resourceCulture);
            }
        }
    }
}
