//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoParts_ShopAndForum.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainLocalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLocalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AutoParts_ShopAndForum.Localization.MainLocalization", typeof(MainLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AllProducts_Navigation {
            get {
                return ResourceManager.GetString("AllProducts_Navigation", resourceCulture);
            }
        }
        
        internal static string Forum_Navigation {
            get {
                return ResourceManager.GetString("Forum_Navigation", resourceCulture);
            }
        }
        
        internal static string AddProduct_Navigation {
            get {
                return ResourceManager.GetString("AddProduct_Navigation", resourceCulture);
            }
        }
        
        internal static string LoginNavigation {
            get {
                return ResourceManager.GetString("LoginNavigation", resourceCulture);
            }
        }
        
        internal static string Register_Navigation {
            get {
                return ResourceManager.GetString("Register_Navigation", resourceCulture);
            }
        }
        
        internal static string Chat_Navigation {
            get {
                return ResourceManager.GetString("Chat_Navigation", resourceCulture);
            }
        }
        
        internal static string ProductCategory_OilsAndLiquids {
            get {
                return ResourceManager.GetString("ProductCategory_OilsAndLiquids", resourceCulture);
            }
        }
        
        internal static string ProductCategory_Filters {
            get {
                return ResourceManager.GetString("ProductCategory_Filters", resourceCulture);
            }
        }
        
        internal static string ProductCategory_WindowsCleaning {
            get {
                return ResourceManager.GetString("ProductCategory_WindowsCleaning", resourceCulture);
            }
        }
        
        internal static string ProductsCategory_Additives {
            get {
                return ResourceManager.GetString("ProductsCategory_Additives", resourceCulture);
            }
        }
        
        internal static string ProductSubcategory_Oils {
            get {
                return ResourceManager.GetString("ProductSubcategory_Oils", resourceCulture);
            }
        }
        
        internal static string ProductSubcategory_Antifreeze {
            get {
                return ResourceManager.GetString("ProductSubcategory_Antifreeze", resourceCulture);
            }
        }
        
        internal static string ProductSubcategory_OilFilters {
            get {
                return ResourceManager.GetString("ProductSubcategory_OilFilters", resourceCulture);
            }
        }
        
        internal static string ProductSubcategory_AirFilters {
            get {
                return ResourceManager.GetString("ProductSubcategory_AirFilters", resourceCulture);
            }
        }
        
        internal static string ProductSubcategory_FrontWindow {
            get {
                return ResourceManager.GetString("ProductSubcategory_FrontWindow", resourceCulture);
            }
        }
        
        internal static string ProductSubcategory_BackWindow {
            get {
                return ResourceManager.GetString("ProductSubcategory_BackWindow", resourceCulture);
            }
        }
        
        internal static string ProductSubcategory_OilAdditives {
            get {
                return ResourceManager.GetString("ProductSubcategory_OilAdditives", resourceCulture);
            }
        }
        
        internal static string ProductSubcategory_CoolantAdditives {
            get {
                return ResourceManager.GetString("ProductSubcategory_CoolantAdditives", resourceCulture);
            }
        }
        
        internal static string PostCategory_BestOils {
            get {
                return ResourceManager.GetString("PostCategory_BestOils", resourceCulture);
            }
        }
        
        internal static string PostCategory_BestFilters {
            get {
                return ResourceManager.GetString("PostCategory_BestFilters", resourceCulture);
            }
        }
        
        internal static string PostCategory_BestAdditives {
            get {
                return ResourceManager.GetString("PostCategory_BestAdditives", resourceCulture);
            }
        }
    }
}
